name: light_sensor
description: A new flutter plugin project.
version: 1.0.2
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.vodemn.light_sensor
        pluginClass: LightSensorPlugin
